### PR TITLE
Remove Original suffix using removeVersion

### LINKED ISSUE #114: Remove "Original" suffix with `removeVersion` suffix
Currently the suffix is removed by the `fixTrackSuffix` function, which is incorrect - the function should only *fix* the suffixes, but not remove.

The `removeVersion` function is a best candidate to have this functionality. The only thing is this function is not used in the Spotify filter; initially I added removing the "Original" suffix to keep clean scrobbles from Spotify. We could include this function in the Spotify filter, though it's a sort of breaking change (?).

### PR DESCRIPTION
**Pull request by FOSSforlife**
Closes #114. Interestingly enough, when I was searching Spotify I didn't find any that had "- Original", but I did find a few that had "- Original Version" and at least one that had "- Original Single Version", so I decided to include those as well.

### CODE REVIEW

File: src/rules.ts [hunk 1]
```diff
@@ -149,6 +147,12 @@ export const VERSION_FILTER_RULES: FilterRule[] = [
 	{ source: /\(Deluxe Edition\)$/, target: '' },
 	// 6 Foot 7 Foot (Explicit Version)
 	{ source: /[([]Explicit Version[)\]]/i, target: '' },
+	// 6 Foot 7 Foot - Original
+	{ source: /-\sOriginal$/i, target: '' },
+	// California Love - Original Version
+	{ source: /-\sOriginal Version$/i, target: '' },
+	// Personal Jesus - Original Single Version
+	{ source: /-\sOriginal Single Version$/i, target: '' },
```
Comment (alexesprit) [inline src/rules.ts:155]: What if we change this rule to remove "Original Whatever Version" ("Whatever" is literally whatever)? E.g. [this album](https://open.spotify.com/album/6LIc6in2ES8hf4ETS8oIyX) contains tracks with such suffix in their names, so the updated rule will also cover this case.

**Comment by alexesprit** [comment]
> Interestingly enough, when I was searching Spotify I didn't find any that had "- Original"

I stumbled upon this suffix while listening to random playlists, and can't remember any specific example. But I found [this single](https://open.spotify.com/album/2d6veFrbZmMkQucorw6HhG), which includes "Original" suffix.

> but I did find a few that had "- Original Version" and at least one that had "- Original Single Version", so I decided to include those as well.

Also, some tracks have "Original Version YYYY"-like suffixes (e.g. tracks from [this album](https://open.spotify.com/album/3I3YSq7ArvlwK3l49pq4oE) and few others I found). Could you add a rule to process them as well?

**Review by alexesprit — APPROVED** [review]

**Comment by alexesprit** [comment]
Thank your for the all PRs!
